# This file is managed by 'repo_helper'. Don't edit it directly.
---

exclude: (\.min.(css|js)|leaflet.geometryutil.js|leaflet.polylineDecorator.js|js/leaflet_bundle.js|js/watercourses_geojson_utils.js)$

ci:
  autoupdate_schedule: quarterly

repos:
 - repo: https://github.com/repo-helper/pyproject-parser
   rev: v0.13.0
   hooks:
    - id: reformat-pyproject

 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.4.0
   hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: fix-byte-order-marker
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: detect-private-key
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: end-of-file-fixer

 - repo: https://github.com/domdfcoding/pre-commit-hooks
   rev: v0.4.0
   hooks:
    - id: requirements-txt-sorter
      args:
       - --allow-git
    - id: check-docstring-first
      exclude: ^(doc-source/conf|__pkginfo__|setup|tests/.*)\.py$
    - id: bind-requirements

 - repo: https://github.com/python-formate/flake8-dunder-all
   rev: v0.4.1
   hooks:
    - id: ensure-dunder-all
      files: ^towpath_walk_tracker/.*\.py$

 - repo: https://github.com/domdfcoding/flake2lint
   rev: v0.4.3
   hooks:
    - id: flake2lint

 - repo: https://github.com/pre-commit/pygrep-hooks
   rev: v1.10.0
   hooks:
    - id: python-no-eval
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

 - repo: https://github.com/asottile/pyupgrade
   rev: v2.12.0
   hooks:
    - id: pyupgrade
      args:
       - --py36-plus
       - --keep-runtime-typing

 - repo: https://github.com/Lucas-C/pre-commit-hooks
   rev: v1.5.1
   hooks:
    - id: remove-crlf
    - id: forbid-crlf

 - repo: https://github.com/python-formate/snippet-fmt
   rev: v0.1.5
   hooks:
    - id: snippet-fmt

 - repo: https://github.com/python-formate/formate
   rev: v0.8.0
   hooks:
    - id: formate
      exclude: ^(doc-source/conf|__pkginfo__|setup)\.(_)?py$

 - repo: https://github.com/python-coincidence/dep_checker
   rev: v0.8.0
   hooks:
    - id: dep_checker
      args:
       - towpath_walk_tracker

# Custom hooks can be added below this comment

 - repo: https://github.com/awebdeveloper/pre-commit-stylelint
   rev: 8f63da497580898a7e0ceef6bf9e72cc0af07828
   hooks:
    - id: stylelint
      additional_dependencies:
       - stylelint@13.13.1
       - stylelint-config-standard@22.0.0
      args:
       - --fix

 - repo: https://github.com/pre-commit/mirrors-eslint
   rev: v8.56.0
   hooks:
    - id: eslint
      files: \.m?[jt]sx?$
      types:
       - file
      args:
       - --fix
      additional_dependencies:
       - eslint@8.57.1
       - eslint-config-standard@17.1.0
       - eslint-plugin-es@4.1.0
       - eslint-plugin-import@2.32.0
       - eslint-plugin-n@17.21.3
       - eslint-plugin-promise@7.2.1
       - '@typescript-eslint/parser@8.20.0'
       - '@typescript-eslint/eslint-plugin@8.20.0'

 - repo: https://github.com/djlint/djLint
   rev: v1.35.2
   hooks:
    - id: djlint-reformat-jinja
    - id: djlint-jinja

 - repo: local
   hooks:
    - id: compile-css
      language: node
      name: Compile SCSS and minify css
      entry: ./rebuild_css.sh
      always_run: true
      pass_filenames: false
      additional_dependencies:
       - sass@1.32.0
